//----------------------
// <auto-generated>
//      Generated by the SourceCodeGenerator project. DO NOT EDIT!
//      Source: CatQL.Core.Models.Cat
// </auto-generated>
//----------------------

namespace CatQL.Presentation.GraphQL.Schema
{
    using global::GraphQL.Types;
    using Core.Models;
    using MediatR;
    using global::GraphQL;
    using Types;

    /// <summary>GraphQL Schema for <see cref="Cat"/></summary>
    public class Schema : global::GraphQL.Types.Schema
    {
        /// <summary>Initializes a new instance of the <see cref="Schema"/> class.</summary>
        /// <param name="mediator">An implementation of <see cref="IMediator"/>.</param>
        public Schema(IMediator mediator)
        {
            this.RegisterTypeMapping<Breed, BreedOutputType>();

            Query = new Queries(mediator);
            Mutation = new Mutations(mediator);
        }
    }
}