//----------------------
// <auto-generated>
//      Generated by the SourceCodeGenerator project. DO NOT EDIT!
//      Source: CatQL.Core.Models.Breed
// </auto-generated>
//----------------------

namespace CatQL.Presentation.GraphQL.Types
{
    using Core.Models;
    using global::GraphQL.Types;

    /// <summary>GraphQL Type for <see cref="Breed"/></summary>
    public class BreedOutputType : ObjectGraphType<Breed>
    {
        /// <summary>Initializes a new instance of the <see cref="BreedOutputType"/> class.</summary>
        public BreedOutputType()
        {
        }
    }
}