//----------------------
// <auto-generated>
//      Generated by the SourceCodeGenerator project. DO NOT EDIT!
//      Source: CatQL.Core.Models.Cat
// </auto-generated>
//----------------------

namespace CatQL.Presentation.GraphQL.Types
{
    using Core.Models;
    using global::GraphQL.Types;

    /// <summary>GraphQL Type for <see cref="Cat"/></summary>
    public class CatInputType : InputObjectGraphType<Cat>
    {
        /// <summary>Initializes a new instance of the <see cref="CatInputType"/> class.</summary>
        public CatInputType()
        {
            Name = "CatInput";
            Field<NonNullGraphType<StringGraphType>>("Name");
            Field<NonNullGraphType<IntGraphType>>("Age");
            Field<NonNullGraphType<StringGraphType>>("Color");
            Field<IntGraphType>("Weight");
            Field<DateGraphType>("Birthdate");
        }
    }
}