//----------------------
// <auto-generated>
//      Generated by the SourceCodeGenerator project. DO NOT EDIT!
//      Source: CatQL.Core.Models.Cat
// </auto-generated>
//----------------------

namespace CatQL.Presentation.GraphQL.Types
{
    using Core.Models;
    using global::GraphQL.Types;

    /// <summary>GraphQL Type for <see cref="Cat"/></summary>
    public class CatOutputType : ObjectGraphType<Cat>
    {
        /// <summary>Initializes a new instance of the <see cref="CatOutputType"/> class.</summary>
        public CatOutputType()
        {
            Field(o => o.Id).Description("Id");
            Field(o => o.Name).Description("The name of the cat");
            Field(o => o.Age).Description("The age of the cat in full years");
            Field(o => o.Color).Description("Color");
            Field(o => o.Birthdate).Description("Birthdate");
            Field<Breed>(o => o.Breed).Description("Breed");
        }
    }
}