//----------------------
// <auto-generated>
//      Generated by the SourceCodeGenerator project. DO NOT EDIT!
//      source: CatQL.Core.Models.Breed
// </auto-generated>
//----------------------

namespace CatQL.Presentation.GraphQL.Schema
{
    using global::GraphQL.Types;
    using Core.Models;
    using MediatR;
    using Queries;

    /// <summary>GraphQL Schema for <see cref="Breed"/></summary>
    public class BreedSchema : Schema
    {
        /// <summary>Initializes a new instance of the <see cref="BreedSchema"/> class.</summary>/// <param name="mediator">An implementation of <see cref="IMediator"/>.</param>
        public BreedSchema(IMediator mediator)
        {
        }
    }
}