//----------------------
// <auto-generated>
//      Generated by the SourceCodeGenerator project. DO NOT EDIT!
//      source: Cat.cs
// </auto-generated>
//----------------------

namespace CatQL.Presentation.GraphQL.Schema
{
    using global::GraphQL.Types;
    using Core.Models;
    using Queries;

    /// <summary>GraphQL Schema for <see cref="Cat"/></summary>
    public class CatSchema2 : Schema
    {
        /// <summary>Initializes a new instance of the <see cref="CatSchema2"/> class.</summary>
        public CatSchema2()
        {
            Query = new CatQuery(mediator);
            Mutation = new CatMutation(mediator);
        }
    }
}